### ISSUE TITLE
Other Vtuber Groups

### ISSUE THREAD

**Issue by diablo050189** [RiceCakess/Holodex-old#13]
Wondering if you had any plans to add any other Vtuber groups. I watch a lot of Nijisanji as well and would love to be able to use Holodex for finding their content as well.

**Comment by RiceCakess** [comment]
At the moment, Holodex will probably be hololive only. I have given it some thought, and the two options is to either make a separate website similar to Holodex but called Nijisanjidex, or merge everything together (but might involve a few challenges that needs to be worked out). 

TLDR: Needs a little bit more thought.

**Comment by kevin41714** [comment]
A solution I was thinking of regarding this issue is, can you add an option to manually add in our own channels to keep track of in Holodex? A very useful feature on Hololive.jetri.co for example is that you can add any youtube video/stream to play alongside Holo members by adding the URL, and I'm wondering if you can do the same for channels on Holodex.

The list of added channels could then be saved to cookies and an individual could have their favorite Hololive channels alongside any other Nijisanji/Indie vtubers they want to watch.

**Comment by RiceCakess** [comment]
Our server does a lot of the tagging and tracking for each channel and video, so cookies by itself would not be able to power some of the features that we have.

However, we are currently working on support for many of your favorite vtubers in the next major upgrade. Stay tuned!

**Comment by RiceCakess** [comment]
Major update has been released, and we now track over 400+ vtuber channels
